Repository fga-eps-mds/2020.1-VC_Usuario, pull requests merged in 2020-10, with the labels that each got.

#109 #104 US01 Rotinas e sistemas de postagens anônimas (back-end).
  .gitignore
  package-lock.json
  package.json
  src/config/multer.js
  src/controllers/postage.js
  src/database/db.js
  src/index.js
  src/models/UPA.js
  src/models/postage.js
  src/models/user.js
  src/routes.js
Labels: development

#118 Adicionando documento canvas
  _sidebar.md
  docs/Canvas.md
  docs/Imagens/Canvas/Business_model_canvas.jpg
Labels: Hacktoberfest, documentation

#117 #104 US01 Postagem Anonima
  .env
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  src/config/multer.js
  src/controllers/postage.js
  src/database/db.js
  src/index.js
  src/models/UPS.js
  src/models/postage.js
  src/models/user.js
  src/routes.js
  tmp/img_uploads/.gitignore
Labels: development

#119 Feature/us03 #116 visualizar postagem
  src/controllers/postage.js
  src/routes.js
Labels: development, hacktoberfest-accepted, user story

#120 Feature/US02 tela inicial/feed postagens
  src/controllers/postage.js
  src/database/db.js
  src/models/postage.js
  src/routes.js
Labels: development

#122 #111 Revisando Readme, Templates e Contributing
  .github/ISSUE_TEMPLATE/general-issue-template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  docs/Documento_de_Arquitetura.md
  docs/Documento_de_Visao.md
  docs/Imagens/Documento_de_Arquitetura/Casos_de_Uso.png
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Rel.jpg
  docs/Imagens/Documento_de_Arquitetura/ModelagemDB.png
  docs/Plano_riscos.md
  docs/Product_Backlog.md
  docs/Reuniao_com_Clientes.md
  docs/Roadmap.md
  docs/politicas/branches.md
  docs/politicas/commits.md
  docs/politicas/issues.md
  docs/politicas/policies.md
  docs/politicas/pull_request.md
  docs/pull_request_template.md
  docs/sprints/sprint_0/Planning_Sprint_0.md
  docs/sprints/sprint_0/Review_Sprint_0.md
  docs/sprints/sprint_1/Planning_Sprint_1.md
  docs/sprints/sprint_1/Review_Sprint_1.md
  docs/sprints/sprint_2/Planning_Sprint_2.md
  docs/sprints/sprint_2/Review_Sprint_2.md
  docs/sprints/sprint_3/Planning_Sprint_3.md
  docs/sprints/sprint_3/Review_Sprint_3.md
Labels: documentation

#123 Release/v0.1.0
  README.md
Labels: development, release 1

#124 Release/v0.1.0
  .dockerignore
  .env
  .github/ISSUE_TEMPLATE/general-issue-template.md
  .github/pull_request_template.md
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  docs/Documento_de_Visao.md
  docs/Documento_de_arquitetura.md
  docs/Reuniao_com_Clientes.md
  docs/Roadmap.md
  package-lock.json
  package.json
  src/config/multer.js
  src/controllers/postage.js
  src/index.js
  src/models/UPS.js
  src/models/postage.js
  src/models/user.js
  src/routes.js
  tmp/img_uploads/.gitignore
Labels: development, release 1

#125 Adicionando documentação da Sprint 6.
  _sidebar.md
  docs/Imagens/Sprints/Burndown_S6.png
  docs/Imagens/Sprints/Daily_Sprint6.png
  docs/Imagens/Sprints/Quadro_conhecimento_S6.png
  docs/sprints/sprint_6/Planning_Sprint_6.md
  docs/sprints/sprint_6/Review_Sprint_6.md
Labels: Scrum Master, documentation, gh page

#133 Atualizando CONTRIBUTING, CODE_OF_CONDUCT da develop.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: README, documentation, hacktoberfest-accepted

#132 129 feedback documentacao
  _sidebar.md
  docs/Canvas.md
  docs/Documento_de_Arquitetura.md
  docs/Documento_de_Visao.md
  docs/Plano_riscos.md
  docs/Prototipos.md
  style/css/general.css
Labels: documentation, gh page, hacktoberfest-accepted, quick

#134 US05 #126 Cadastro
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/models/user.js
  src/routes.js
Labels: development, hacktoberfest-accepted, user story

#138 #135 Atualizando o roadmap
  docs/Roadmap.md
Labels: documentation, gh page, hacktoberfest-accepted, quick

#145 #141 adicionando code climate ao readme
  README.md
Labels: README, documentation, hacktoberfest-accepted

#142 US06 #130 fazer/desfazer login
  package-lock.json
  package.json
  src/config/auth.json
  src/controllers/auth_controller.js
  src/controllers/user_controller.js
  src/models/user.js
  src/routes.js
Labels: development, hacktoberfest-accepted

#147 Documentacao sprint 7
  docs/Imagens/Sprints/Burndown_S7.png
  docs/Imagens/Sprints/Daily_Sprint7.png
  docs/Imagens/Sprints/Quadro_conhecimento_S7.png
  docs/sprints/sprint_7/Planning_Sprint_7.md
  docs/sprints/sprint_7/Review_Sprint_7.md
Labels: documentation

#157 Atualização de documentos
  README.md
  docs/Documento_de_Arquitetura.md
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Front.png
  docs/Roadmap.md
  index.html
  style/icons/WordMark.png
  style/icons/Wordmark_in.png
  style/icons/wordmarkVC.png
Labels: README, documentation, gh page, hacktoberfest-accepted

#158 149 documentacao sprint 8
  docs/Imagens/Sprints/Burndown_S8.png
  docs/Imagens/Sprints/Daily_Sprint8.png
  docs/Imagens/Sprints/Quadro_conhecimento_S8.png
  docs/sprints/sprint_8/Planning_Sprint_8.md
  docs/sprints/sprint_8/Review_Sprint8.md
Labels: documentation, gh page

#160 US08 Apoiar Postagem
  src/controllers/UPS_controller.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/models/UPS.js
  src/models/postage.js
  src/models/user.js
  src/routes.js
Labels: development, hacktoberfest-accepted, user story
