Repository fga-eps-mds/2020.1-VC_Usuario, pull requests merged in 2020-11, with the labels that each got.

#167 #164 Documentação Sprint 9
  _sidebar.md
  docs/Imagens/Sprints/Burndown_S9.png
  docs/Imagens/Sprints/Daily_Sprint9.png
  docs/Imagens/Sprints/Quadro_conhecimento_S9.png
  docs/sprints/sprint_8/Review_Sprint_8.md
  docs/sprints/sprint_9/Planning_Sprint_9.md
  docs/sprints/sprint_9/Review_Sprint_9.md
Labels: Scrum Master, documentation

#170 Feature/us13 us14 #154 excluir/#155 editar conta
  src/controllers/auth_controller.js
  src/controllers/user_controller.js
  src/routes.js
Labels: development, user story

#171 #169 Listando Postagens Logado
  src/controllers/postage_controller.js
Labels: bug, development

#172 Feature/us15 #161 filtrar postagens
  src/controllers/postage_controller.js
  src/routes.js
Labels: development, user story

#173 US11 US12 #166 Excluir e Editar Postagem
  src/controllers/UPS_controller.js
  src/controllers/postage_controller.js
  src/index.js
  src/routes.js
Labels: development, user story

#182 #181 Issues do Code Climate em support_postage
  src/controllers/UPS_controller.js
Labels: bug, development

#183 Atualizacao da documentacao
  _sidebar.md
  docs/Imagens/Sprints/Burndown_S10.png
  docs/Imagens/Sprints/Daily_Sprint10.png
  docs/Imagens/Sprints/Quadro_conhecimento_S10.png
  docs/Roadmap.md
  docs/sprints/sprint_10/Planning_Sprint_10.md
  docs/sprints/sprint_10/Review_Sprint_10.md
Labels: Scrum Master, documentation, organization

#180 #178 Issue de duplicação de código do Code Climate
  src/controllers/postage_controller.js
  src/routes.js
Labels: bug, development

#185 Feature/us10#179 pontuacao
  src/controllers/UPS_controller.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
Labels: development, user story

#186 174 implementar deploy
  Procfile
  src/controllers/postage_controller.js
  src/index.js
Labels: development

#193 189 documentacao sprint 11
  _sidebar.md
  docs/Imagens/Sprints/Burndown_S11.png
  docs/Imagens/Sprints/Daily_Sprint11.png
  docs/Imagens/Sprints/Quadro_conhecimento_S11.png
  docs/Roadmap.md
  docs/sprints/sprint_11/Planning_Sprint_11.md
  docs/sprints/sprint_11/Review_Sprint_11.md
Labels: Scrum Master, documentation

#194 US22 #192 Usuário comentar postagem
  src/controllers/UPC_controller.js
  src/controllers/postage_controller.js
  src/models/UPC.js
  src/models/UPS.js
  src/models/postage.js
  src/routes.js
Labels: development, user story

#201 #195 Arrumando erro no método check_user_of_postage
  src/controllers/postage_controller.js
Labels: bug, development
