Repository fga-eps-mds/2020.1-VC_Usuario, pull requests merged in 2020-12, with the labels that each got.

#203 #198 Documentação Atualização Documentos
  docs/Imagens/Sprints/Burndown_S12.png
  docs/Imagens/Sprints/Daily_Sprint12.png
  docs/Imagens/Sprints/Quadro_conhecimento_S12.png
  docs/Product_Backlog.md
  docs/Roadmap.md
  docs/sprints/sprint_12/Planning_Sprint_12.md
  docs/sprints/sprint_12/Review_Sprint_12.md
  docs/sprints/sprint_13/Planning_Sprint_13.md
  docs/sprints/sprint_13/Review_Sprint_13.md
Labels: documentation

#204 197 arrumando bugs backend
  src/controllers/UPC_controller.js
  src/controllers/UPS_controller.js
  src/controllers/auth_controller.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/index.js
  src/models/UPC.js
  src/models/postage.js
  src/models/user.js
  src/routes.js
Labels: bug, development

#205 US22 #192 Usuario Logado Comentar Postagem
  src/controllers/UPC_controller.js
  src/controllers/postage_controller.js
  src/models/UPC.js
Labels: development, user story

#206 US20 #199 Denunciar Postagem
  src/controllers/UPR_controller.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/models/UPR.js
  src/models/postage.js
  src/routes.js
Labels: development, user story

#214 212 documentacao sprint 14
  _sidebar.md
  docs/Imagens/Sprints/Burndown_S14.png
  docs/Imagens/Sprints/Daily_Sprint14.png
  docs/Imagens/Sprints/Quadro_conhecimento_S14.png
  docs/sprints/sprint_14/Planning_Sprint_14.md
  docs/sprints/sprint_14/Review_Sprint_14.md
Labels: Scrum Master, documentation

#213 Testes
  .env
  .gitignore
  __TEST__/data/data.js
  __TEST__/data/giphy.gif
  __TEST__/data/logoVC.png
  __TEST__/routes/main_route.test.js
  __TEST__/routes/postages_routes.test.js
  __TEST__/routes/upc_routes.test.js
  __TEST__/routes/upr_router.test.js
  __TEST__/routes/ups_routes.test.js
  __TEST__/routes/user_routes.test.js
  jest-mongodb-config.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/app.js
  src/config/dev.env
  src/config/multer.js
  src/config/test.env
  src/controllers/UPC_controller.js
  src/controllers/UPR_controller.js
  src/controllers/UPS_controller.js
  src/controllers/auth_controller.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/db/connection.js
  src/db/models/UPC.js
  src/db/models/UPR.js
  src/db/models/UPS.js
  src/db/models/postage.js
  src/db/models/user.js
  src/index.js
  src/routes.js
Labels: devops, enhancement

#215 Ajustes gerais
  __TEST__/routes/main_route.test.js
  __TEST__/routes/user_routes.test.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/routes.js
Labels: bug, development, enhancement, release 2

#217 #216 Resolvendo bug de atualizar status da postagem
  src/controllers/postage_controller.js
Labels: enhancement

#219 #210 Atualizar Readme
  CONTRIBUTING.md
  README.md
Labels: README, release 2

#220 Release 2
  .env
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Procfile
  README.md
  __TEST__/data/data.js
  __TEST__/data/giphy.gif
  __TEST__/data/logoVC.png
  __TEST__/routes/main_route.test.js
  __TEST__/routes/postages_routes.test.js
  __TEST__/routes/upc_routes.test.js
  __TEST__/routes/upr_router.test.js
  __TEST__/routes/ups_routes.test.js
  __TEST__/routes/user_routes.test.js
  jest-mongodb-config.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/app.js
  src/config/auth.json
  src/config/dev.env
  src/config/multer.js
  src/config/test.env
  src/controllers/UPC_controller.js
  src/controllers/UPR_controller.js
  src/controllers/UPS_controller.js
  src/controllers/auth_controller.js
  src/controllers/postage.js
  src/controllers/postage_controller.js
  src/controllers/user_controller.js
  src/db/connection.js
  src/db/models/UPC.js
  src/db/models/UPR.js
  src/db/models/UPS.js
  src/db/models/postage.js
  src/db/models/user.js
  src/index.js
  src/routes.js
Labels: release 2
