Repository fga-eps-mds/2020.1-VC_Usuario, pull requests merged in 2020-09, with the labels that each got.

#37 #35 Inserindo template do documento de visão e modificando nome dos arquivos
  docs/Documento_de_Visao.md
  docs/Reuniao_com_Clientes.md
  docs/VisionDocument.md
Labels: documentation

#47 #41 Inserindo os itens 3.5, 3.6 e 3.7 do documeno de visão.
  docs/Documento_de_Visao.md
  docs/Documento_de_arquitetura.md
Labels: documentation

#48 #41 Inserindo o item 2.2 no Documento de Visão
  docs/Documento_de_Visao.md
Labels: documentation

#50 #41 Inserindo os itens 3.1, 3.2, 3.3 e 3.4 no Documento de Visão
  docs/Documento_de_Visao.md
Labels: documentation

#51 #41 Atualizando Histórico de Revisão - 0.6 Enzo Gabriel
  docs/Documento_de_Visao.md
Labels: documentation

#61 #41 Inserindo os itens 1.3 e 1.4 no documento de visão
  docs/Documento_de_Visao.md
Labels: documentation

#63 #55 Criando e organizando uma nova branch para ser a fonte da GitHub page de documentação.
  .nojekyll
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  _coverpage.md
  _sidebar.md
  docs/Documento_de_Visao.md
  index.html
Labels: documentation, gh page

#69 #56 adicionando documento do plano de riscos
  docs/Plano_riscos.md
Labels: documentation, gh page, study

#71 #58 #59 Desenvolvendo Product Backlog e Formatando Documento de Visão
  README.md
  docs/Documento_de_Visao.md
  docs/Product_Backlog.md
Labels: Product Owner, documentation, user story

#73 #58 Adicionando pontuação nas Histórias de Usuário do Product Backlog
  docs/Product_Backlog.md
Labels: Product Owner, documentation, user story

#76 #62 incluindo os documentos de políticas para contribuição
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/issues.md
  docs/policies/policies.md
  docs/policies/pull_request.md
Labels: documentation

#81 #62 Adicionando o template de pull request a branch develop e #64 adicionando os requisitos ao documento de arquitetura
  docs/Documento_de_arquitetura.md
  docs/pull_request_template.md
Labels: documentation

#83 #57 Adicionando Planning e Review das Sprints 0, 1 e 2
  docs/sprints/sprint_0/Planning_Sprint_0.md
  docs/sprints/sprint_0/Review_Sprint_0.md
  docs/sprints/sprint_1/Planning_Sprint_1.md
  docs/sprints/sprint_1/Review_Sprint_1.md
  docs/sprints/sprint_2/Planning_Sprint_2.md
  docs/sprints/sprint_2/Review_Planning_2.md
Labels: documentation

#82 #59 Revisando e desenvolvendo todo o documento - Documento de Visão
  docs/Documento_de_Visao.md
Labels: documentation

#91 #64 Refatorando o documento de arquitetura.
  docs/Documento_de_Arquitetura.md
  docs/Documento_de_arquitetura.md
  docs/Imagens/Documento_de_Arquitetura/Casos_de_Uso.png
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Rel.jpg
  docs/Imagens/Documento_de_Arquitetura/ModelagemDB.png
Labels: documentation, gh page

#96 #88 92 #72 Revisão das políticas do Projeto e do Documento de Visão | Criando ambiente de desenvolvimento do node.js
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  docs/Documento_de_Visao.md
  docs/policies/branches.md
  docs/policies/issues.md
  docs/policies/policies.md
  docs/policies/pull_request.md
  docs/politicas/branches.md
  docs/politicas/commits.md
  docs/politicas/issues.md
  docs/politicas/policies.md
  docs/politicas/pull_request.md
  package-lock.json
  package.json
  src/index.js
Labels: development, devops, documentation, organization

#97 #64 Atualizando o documento de arquitetura.
  docs/Documento_de_Arquitetura.md
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Rel.jpg
  docs/Imagens/Documento_de_Arquitetura/ModelagemDB.png
Labels: documentation, gh page

#99 #90 #73 Revisão do Product Backlog, Configurando docker-compose e Adição template PR
  .github/pull_request_template.md
  docker-compose.yml
  docs/Documento_de_Visao.md
  docs/Product_Backlog.md
Labels: Product Owner, devops, user story

#98 #86 Refatorando Roadmap
  docs/Roadmap.md
Labels: documentation

#102 #90 #72 Revisando Product Backlog e Configurando docker-compose
  .github/pull_request_template.md
  Makefile
  docker-compose.yml
  docs/Documento_de_Visao.md
  docs/Product_Backlog.md
  src/index.js
Labels: Product Owner, development, devops

#103 #86 Revisando o Roadmap
  docs/Roadmap.md
Labels: documentation

#105 #84 Atualização da página de documentação.
  README.md
  _config.yml
  _coverpage.md
  _sidebar.md
  docs/Documento_de_Arquitetura.md
  docs/Documento_de_Visao.md
  docs/Documento_de_arquitetura.md
  docs/Identidade_Visual.md
  docs/Imagens/Documento_de_Arquitetura/Casos_de_Uso.png
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Back.png
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Front.png
  docs/Imagens/Documento_de_Arquitetura/Diagrama_Rel.jpg
  docs/Imagens/Documento_de_Arquitetura/ModelagemDB.png
  docs/Plano_riscos.md
  docs/Product_Backlog.md
  docs/Prototipos.md
  docs/Roadmap.md
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/issues.md
  docs/policies/policies.md
  docs/policies/pull_request.md
  docs/pull_request_template.md
  docs/sprints/sprint_0/Planning_Sprint_0.md
  docs/sprints/sprint_0/Review_Sprint_0.md
  docs/sprints/sprint_1/Planning_Sprint_1.md
  docs/sprints/sprint_1/Review_Sprint_1.md
  docs/sprints/sprint_2/Planning_Sprint_2.md
  docs/sprints/sprint_2/Review_Sprint_2.md
  docs/sprints/sprint_3/Planning_Sprint_3.md
  docs/sprints/sprint_3/Review_Sprint_3.md
  index.html
  style/css/general.css
  style/icons/Wordmark_in.png
  style/icons/logoVC.png
  style/icons/wordmarkVC.png
Labels: documentation, gh page
